### ISSUE TITLE
ATD running single instance with iOS 13.6 and above 

### ISSUE THREAD

**Issue by chuklov** [AppiumTestDistribution/AppiumTestDistribution#758]
Hi, I have a few iPhones with version iOS 13.6 and 14.0 and I cannot run both. Only one will run tests. 
What logs are you need to check it? 

Also ofter when 2 phones are connected test are being stopped as session was closed. If only one phone is connected it works fine. 

Thanks

**Comment by saikrishna321** [comment]
@chuklov Please give the logs when you trigger the test. Also the capabilites.json. When you cannot run both --> what happens

**Comment by chuklov** [comment]
@saikrishna321 can you please specify what logs I should upload? 
When 2 phones connected only one running tests. Second remains untouched. Its randomly choosing which will be used.

**Comment by chuklov** [comment]
Capabilities.json

`{
  "android": {
      "--relaxed-security": true,
      "--session-override": true,
      "platformName": "android",
      "platformVersion": "6",
      "browserName": "chrome",
      "deviceName": { "Huawei": "LCL0218529000550",
                      "SamsungS7": "ce11160b8bca471305",
                      "LG-G4":  "LGH81598bce4d",
                      "LG-G5":  "LGH86038521565",
                      "Samsung Note9":  "2625d0515b1c7ece",
                      "Xiomi A2":  "3419e39",
                      "Xiomi A3": "c07886bb2111",
                      "SamsungNote9":  "2625d0515b1c7ece",
                      "OnePlus":  "8b383b26",
                      "SM-A520F": "520048e9fe7a258d",
                      "ASUS_I01WD": "K7AIHM00H852H23"
      },
      "automationName": "Appium",
      "noReset": true,
      "unlockType": "pin",
      "unlockKey": "1234",
      "newCommandTimeout": 600,
      "nativeWebScreenshot": true,
      "androidScreenshotPath": "target/screenshots",
      "autoGrantPermissions": true,
      "w3c": true,
      "chromedriverExecutable": "/usr/local/bin/chromedriver",
      "chromeOptions": {"w3c": false}
    },
  "iOS": {
    "platformName": "ios",
    "bundleId": "com.apple.mobilesafari",
    "deviceName": "iPhone",
    "udid": "bd3ccfde1c14ef869656292b0460da522728aedc",
    "noReset": true,
    "xcodeSigningId": "iPhone Developer",
    "platformVersion": "13",
    "appiumVersion": "1.18.3",
    "automationName": "XCUITest",
    "usePrebuiltWDA": true,
    "clearSystemFiles": true,
    "preventWDAAttachments": true,
    "useNewWDA": false,
    "xcodeOrgId": "2ES97B4EP7",
    "agentPath": "/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj",
    "bootstrapPath": "/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/",
    "newCommandTimeout": 600,
    "showIOSLog": true,
    "showXCODELog": true
  },
  "hostMachines": [
    {
      "machineIP": "127.0.0.1"
    }
  ]
}`

**Comment by chuklov** [comment]
Looks like I have mistaken, when I have 2 phones it is going one after another. I have about 30 tests and first phone will run all 30 tests and only after the second will start execute them. 
Thus, I do not see separation by Threads in this case.

**Comment by chuklov** [comment]
Here is the log file [https://drive.google.com/file/d/1GyT9pRqQSmnN_9gKk3dc44njJNSD5PfP/view?usp=sharing](url)

**Comment by saikrishna321** [comment]
@chuklov Can you please test with master commit. This issue is fixed

**Comment by chuklov** [comment]
@saikrishna321  Just tested with version 11.0.2 and I do not see any changes. If I have 1 test to run it will run on 1 device instead of 3 I have connected.

**Comment by saikrishna321** [comment]
@chuklov  Can you try with version 

```
	<dependency>
	    <groupId>com.github.AppiumTestDistribution</groupId>
	    <artifactId>AppiumTestDistribution</artifactId>
	    <version>5d9c2c476c</version>
	</dependency>
```

**Comment by chuklov** [comment]
Could not find artifact
com.github.saikrishna321:AppiumTestDistribution:pom:5d9c2c476c in
bintray-epam-reportportal (https://dl.bintray.com/epam/reportportal)

**Comment by saikrishna321** [comment]
https://jitpack.io/#AppiumTestDistribution/AppiumTestDistribution/5d9c2c476c Try adding jitpack repo

**Comment by chuklov** [comment]
New version totally broke my project
Compilation failed: errors: 80; warnings: 33

Previous version has no problems at all.

**Comment by saikrishna321** [comment]
What errors?

**Comment by chuklov** [comment]
[image: image.png]

**Comment by saikrishna321** [comment]
@chuklov Please re-attached.  I can compile with v12.0.0
